name: 'Terraform'

on:
  push:
    branches: [ "main" ]


jobs:
  terraform:
    name: 'Terraform'
    env:
      # AWS secrets
      AWS_ACCESS_KEY_ID: mock_key
      AWS_SECRET_ACCESS_KEY: mock_secret
      AWS_DEFAULT_REGION: us-east-1
      AWS_ENDPOINT_URL: http://localhost:4566
      LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT: "1"

    runs-on: ubuntu-latest
    environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Start LocalStack
      uses: localstack/action@v0.1.7

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.7"

    - name: Terraform init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_action_version: 1.5.7
        tf_action_subcommand: 'init'
        tf_action_working_dir: '.'
        tf_action_comment: true

    - name: Terraform plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_action_version: 1.5.7
        tf_action_subcommand: 'plan'
        tf_action_working_dir: '.'
        tf_action_comment: true

    - name: Terraform apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_action_version: 1.5.7
        tf_action_subcommand: 'apply'
        tf_action_working_dir: '.'
        tf_action_comment: true
        
    

